name: "Publish"

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*

# TODO: publish wheels for more platforms
# TODO: test built wheel
jobs:
  run:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
      
      - name: Install patchelf
        run: sudo apt-get install -y patchelf

      - name: Build format-lib
        run: make format-lib

      - name: Run tests
        run: uv run --locked --all-extras --dev pytest

      - name: Build wheel
        run: uv build --wheel 

      - name: Auditwheel repair wheel
        run: uv run --dev auditwheel repair dist/*.whl

      - name: Publish repaired wheel to PyPi
        run: uv publish wheelhouse/*
